In [3]:
import numpy as np

In [45]:
n = 5
k = 6
s=(n,2)
X = np.zeros(s)

In [46]:
X

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [47]:
centroid_objects = [X[obj_id, :] for obj_id in np.random.randint(0, n, size = k)]

In [48]:
centroid_objects

[array([0., 0.]),
 array([0., 0.]),
 array([0., 0.]),
 array([0., 0.]),
 array([0., 0.]),
 array([0., 0.])]

In [17]:
    centroid_objects = [
        X[obj_id, :]
        for obj_id in np.random.randint(0, n, size=k)
    ]

TypeError: list indices must be integers or slices, not tuple