In [2]:
import numpy as np

In [3]:
n = 5
k = 6
s=(n,2)
X = np.zeros(s)

In [4]:
X

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
centroid_objects = [X[obj_id, :] for obj_id in np.random.randint(0, n, size = k)]

In [20]:
import os
print(os.getcwd())

c:\ML\Ml алгоритмы\ML_algoritms\Klastering


In [6]:
centroid_objects

[array([0., 0.]),
 array([0., 0.]),
 array([0., 0.]),
 array([0., 0.]),
 array([0., 0.]),
 array([0., 0.])]

In [41]:
import matplotlib.pyplot as plt
%matplotlib inline
from func_kla import k_means
import pickle

In [42]:
file_path = 'C:\ML\Ml алгоритмы\ML_algoritms\Klastering\clustering.pkl'
with open(file_path, 'rb') as f:
    data_clustering = pickle.load(f)

C:\Users\user\AppData\Local\Temp\ipykernel_10580\3930855665.py:3: DeprecationWarning: numpy.core._multiarray_umath is deprecated and has been renamed to numpy._core._multiarray_umath. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core._multiarray_umath._reconstruct.
  data_clustering = pickle.load(f)


In [43]:
X = np.array(data_clustering['X'])
print('num points: %d' % X.shape[0])

Y = np.array(data_clustering['Y'])

num points: 100


In [45]:
arr = np.array([1, 2, 3])  # shape = (3,)
row_vector = arr[np.newaxis, :]  # Превращаем в строку: shape = (1, 3)
column_vector = arr[:, np.newaxis]  # Превращаем в столбец: shape = (3, 1)

print("Row vector:", row_vector)
# Output: [[1 2 3]]

print("Column vector:", column_vector)
# Output:
# [[1]
#  [2]
#  [3]]


Row vector: [[1 2 3]]
Column vector: [[1]
 [2]
 [3]]


AttributeError: module 'numpy.random' has no attribute 'randit'